# Charcoal Monolith:- (L0) Foundation App
services:
  # CLI:- Engine Service
  engine:
    build:
      context: ../
      dockerfile: docker/containers/engine/Dockerfile
    restart: always
    volumes:
      - ../src/interfaces/engine:/home/charcoal/interfaces/engine
      - ../emails:/home/charcoal/emails
      - ../storage:/home/charcoal/storage
      - ../tmp:/home/charcoal/tmp
      - ../log/engine:/home/charcoal/log
      - ../docker/containers/engine/vendor:/home/charcoal/vendor
    env_file:
      - .env
    networks:
      charcoal-foundation-vlan:
        ipv4_address: "${SERVICE_ENGINE_IP}"
  # HTTP:- Web Service
  web:
    build:
      context: ../
      dockerfile: docker/fpm-nginx/Dockerfile
      args:
        APP_INTERFACE_DIRECTORY: web
    restart: always
    volumes:
      - ../src/interfaces/web:/home/charcoal/interfaces/web
      - ../public_html:/home/charcoal/public_html
      - ../templates:/home/charcoal/templates
      - ../emails:/home/charcoal/emails
      - ../storage:/home/charcoal/storage
      - ../tmp:/home/charcoal/tmp
      - ../log/web:/home/charcoal/log
      - ../docker/containers/web/vendor:/home/charcoal/vendor
    env_file:
      - .env
    ports:
      - "${SERVICE_WEB_PORT}:6000"
    networks:
      charcoal-foundation-vlan:
        ipv4_address: "${SERVICE_WEB_IP}"

# Networks Configuration
networks:
  charcoal-foundation-vlan:
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_SUBNET}"
