<!--
  ~ Part of the "charcoal-dev/charcoal-foundation" package.
  ~ @link https://github.com/charcoal-dev/charcoal-foundation
  -->
<?php
/**
 * @var array $exception
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Charcoal App Error</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            font-weight: 200;
            font-size: 1.1rem;
        }

        h1, h2, h3, h4, h5, h6 {
            font-weight: 300 !important;
        }

        .stack-trace {
            white-space: pre-wrap;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <div class="p-5 mb-4 bg-danger text-white rounded-3">
        <h1 class="display-6">
            ⚠️ <?= htmlspecialchars(\Charcoal\Base\Objects\ObjectHelper::baseClassName($exception['class'])) ?></h1>
        <p class="lead"><?= htmlspecialchars($exception['message']) ?></p>
        <hr>
        <p><strong>Exception Type:</strong> <?= htmlspecialchars($exception['class']) ?></p>
        <?php if (!empty($exception['file'])): ?>
            <p><strong>File:</strong> <?= htmlspecialchars($exception['file']) ?>
                <?php if (!empty($exception['line'])): ?>
                    :<?= (int)$exception['line'] ?>
                <?php endif; ?>
            </p>
        <?php endif; ?>
        <p class="mb-0"><strong>Error Code:</strong> <?= htmlspecialchars($exception['code']) ?></p>
    </div>

    <?php if (isset($exception['trace']) && is_array($exception['trace'])): ?>
        <h4>Stack Trace:</h4>
        <div class="stack-trace px-4 py-3"><?= htmlspecialchars(json_encode($exception['trace'], JSON_PRETTY_PRINT)) ?></div><?php endif; ?>
    <?php if (isset($exception['previous']) && is_array($exception['previous'])): ?>
        <h4 class="mt-4">Previous Exception:</h4>
        <div class="stack-trace px-4 py-3 mb-4"><strong><?= htmlspecialchars($exception['previous']['class']) ?>:</strong>
            <?= htmlspecialchars($exception['previous']['message']) ?>
            <br><strong>Code:</strong> <?= htmlspecialchars($exception['previous']['code']) ?>
            <br><?php if (!empty($exception['previous']['trace'])): ?><strong>Stack Trace:</strong>
                <br><?= htmlspecialchars(json_encode($exception['previous']['trace'], JSON_PRETTY_PRINT)) ?><?php endif; ?>
        </div>
    <?php endif; ?>
</div>

</body>
</html>