services:
  engine:
    build: { target: dev }
    volumes:
      - ../../dev/composer/vendor:/home/charcoal/dev/composer/vendor:ro
      - ../../config:/home/charcoal/config:ro
      - ../../app/sapi/engine:/home/charcoal/app/sapi/engine:ro
      - ../../app/domain:/home/charcoal/app/domain:ro
      - ../../app/shared:/home/charcoal/app/shared:ro
      - ../../interfaces/engine:/home/charcoal/engine:ro
      - ../../var/log/engine:/home/charcoal/log
      - ../../var/tmp/engine:/home/charcoal/tmp
      - ../../var/shared:/home/charcoal/shared
      - ../../var/storage:/home/charcoal/storage
  web:
    build: { target: dev }
    volumes:
      - ../../dev/composer/vendor:/home/charcoal/dev/composer/vendor:ro
      - ../../config:/home/charcoal/config:ro
      - ../../app/sapi/web:/home/charcoal/app/sapi/web:ro
      - ../../app/domain:/home/charcoal/app/domain:ro
      - ../../app/shared:/home/charcoal/app/shared:ro
      - ../../interfaces/web/public_html:/home/charcoal/web/public_html:ro
      - ../../interfaces/web/templates:/home/charcoal/web/templates:ro
      - ../../var/log/web:/home/charcoal/log
      - ../../var/tmp/web:/home/charcoal/tmp
      - ../../var/shared:/home/charcoal/shared
      - ../../var/storage:/home/charcoal/storage:ro
  mysql:
    volumes:
      - ../../dev/docker/utils/db/init:/docker-entrypoint-initdb.d:ro
