# Charcoal Monolith App
core:
  # Core/Foundation (L0) Configuration Files
  imports:
    - core/cache.yml
    - core/ciphers.yml
    - core/databases.yml
    - core/http.yml
    - core/mailer.yml

# Timezone identifier for entire application
timezone: "UTC"