# Charcoal Monolith App
core:
  # Core/Foundation (L0) Configuration Files
  imports:
    - foundation/cache.yml
    - foundation/ciphers.yml
    - foundation/databases.yml
    - foundation/http.yml
    - foundation/mailer.yml

# Timezone identifier for entire application
timezone: "UTC"