# Charcoal Monolith:- (L0) Foundation App
services:
  # (SAPI) Cli:- Engine Service
  engine:
    profiles: ["engine"]
    env_file: [../.env]
    build:
      context: ../../
      dockerfile: dev/docker/sapi/app/engine/Dockerfile
    restart: always
    networks:
      charcoal-app-internal:
        ipv4_address: "${SAPI_ENGINE_IP}"
      charcoal-app-edge: {}
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 3s
      retries: 5

  # (SAPI) Http:- Web Service
  web:
    profiles: ["web"]
    env_file: [../.env]
    build:
      context: ../../
      dockerfile: dev/docker/sapi/app/web/Dockerfile
    restart: always
    depends_on:
      engine: { condition: service_started }
    networks:
      charcoal-app-internal:
        ipv4_address: "${SAPI_WEB_IP}"
      charcoal-app-edge:
        ipv4_address: "${EDGE_WEB_IP}"
    ports:
      - "55000:6000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5999/health >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10

  # (Aux) MySQL:- Database
  mysql:
    profiles: ["mysql"]
    image: mysql:8.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=charcoal
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - charcoal-mysql-databases:/var/lib/mysql
    networks:
      charcoal-app-internal:
        ipv4_address: "${SERVICE_MYSQL_IP}"

  # (Aux) PhpMyAdmin:- MySQL Administration
  phpmyadmin:
    profiles: ["pma"]
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "${EDGE_PMA_BIND:-127.0.0.1}:${EDGE_PMA_PORT:-10786}:80"
    depends_on:
      mysql: { condition: service_started }
    networks:
      charcoal-app-internal:
        ipv4_address: "${SERVICE_PMA_IP}"
      charcoal-app-edge:
        ipv4_address: "${EDGE_PMA_IP}"

  # (Aux) Redis:- Caching Engine
  redis:
    profiles: ["redis"]
    build:
      context: ../../dev/docker/utils/redis
      dockerfile: Dockerfile
    restart: always
    networks:
      charcoal-app-internal:
        ipv4_address: "${SERVICE_REDIS_IP}"

# Networks Configuration
networks:
  charcoal-app-internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: "${CHARCOAL_CIDR_PRIVATE}"
  charcoal-app-edge:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: "${CHARCOAL_CIDR_EDGE}"

# Auxiliary Volumes
volumes:
  charcoal-mysql-databases: {}
