services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../docker/containers/db/init:/docker-entrypoint-initdb.d
      - charcoal-app-db:/var/lib/mysql
    networks:
      charcoal-foundation-vlan:
        ipv4_address: "${SERVICE_MYSQL_IP}"
  redis:
    build:
      context: ../docker/containers/redis
      dockerfile: Dockerfile
    restart: always
    networks:
      charcoal-foundation-vlan:
        ipv4_address: "${SERVICE_REDIS_IP}"

# Volumes Configuration
volumes:
  charcoal-app-db:
